version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]

  # Node
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in this directory
    directory: "/src/FeatureFlags.Web/"
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns: ["*"]

  # DotNet SDK
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday" # updates are mostly released on Tuesday
    groups:
      dotnet:
        patterns: ["*"]

  # DotNet
  - package-ecosystem: "nuget"
    # Look for a solution file in this directory
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nuget:
        patterns: ["*"]
