//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeatureFlags.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Flags {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Flags() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeatureFlags.Resources.Flags", typeof(Flags).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the feature flag cache?.
        /// </summary>
        public static string ConfirmClearCache {
            get {
                return ResourceManager.GetString("ConfirmClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this filter?.
        /// </summary>
        public static string ConfirmDeleteFilter {
            get {
                return ResourceManager.GetString("ConfirmDeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disable this flag?.
        /// </summary>
        public static string ConfirmDisable {
            get {
                return ResourceManager.GetString("ConfirmDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to enable this flag?.
        /// </summary>
        public static string ConfirmEnable {
            get {
                return ResourceManager.GetString("ConfirmEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Flag.
        /// </summary>
        public static string CreateFlag {
            get {
                return ResourceManager.GetString("CreateFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Flag.
        /// </summary>
        public static string EditFlag {
            get {
                return ResourceManager.GetString("EditFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred deleting flag..
        /// </summary>
        public static string ErrorDeletingFlag {
            get {
                return ResourceManager.GetString("ErrorDeletingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag with this name already exists..
        /// </summary>
        public static string ErrorDuplicateName {
            get {
                return ResourceManager.GetString("ErrorDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required to create a flag..
        /// </summary>
        public static string ErrorNameRequired {
            get {
                return ResourceManager.GetString("ErrorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature flag not found..
        /// </summary>
        public static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred saving flag..
        /// </summary>
        public static string ErrorSavingFlag {
            get {
                return ResourceManager.GetString("ErrorSavingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters are conditions for determining the state of the feature flag.  Flags with no filters will always evaluate to false.  Create at least one filter to enable the flag..
        /// </summary>
        public static string FilterIntro {
            get {
                return ResourceManager.GetString("FilterIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Type.
        /// </summary>
        public static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag.
        /// </summary>
        public static string FlagLower {
            get {
                return ResourceManager.GetString("FlagLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string FlagsPlural {
            get {
                return ResourceManager.GetString("FlagsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Filter.
        /// </summary>
        public static string PercentageFilter {
            get {
                return ResourceManager.GetString("PercentageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement Type.
        /// </summary>
        public static string RequirementType {
            get {
                return ResourceManager.GetString("RequirementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache cleared successfully..
        /// </summary>
        public static string SuccessClearingCache {
            get {
                return ResourceManager.GetString("SuccessClearingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag deleted successfully..
        /// </summary>
        public static string SuccessDeletingFlag {
            get {
                return ResourceManager.GetString("SuccessDeletingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag saved successfully..
        /// </summary>
        public static string SuccessSavingFlag {
            get {
                return ResourceManager.GetString("SuccessSavingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeting Filter.
        /// </summary>
        public static string TargetingFilter {
            get {
                return ResourceManager.GetString("TargetingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Window Filter.
        /// </summary>
        public static string TimeWindowFilter {
            get {
                return ResourceManager.GetString("TimeWindowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Flags.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
    }
}
