//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeatureFlags.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Flags {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Flags() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeatureFlags.Resources.Flags", typeof(Flags).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the JSON filter to create more complex filters than the UI currently allows.  The JSON value will be added to the list of client_filters..
        /// </summary>
        public static string AboutJson {
            get {
                return ResourceManager.GetString("AboutJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the percentage filter to turn a feature on or off based on a set percentage. Users will be randomly included based on the percentage. Authenticated users will consistently see the same behavior. Anonymous users will be random..
        /// </summary>
        public static string AboutPercentage {
            get {
                return ResourceManager.GetString("AboutPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the targeting filter to turn a feature on or off for specific users.  Any user in the target list will evaluate to true.  Any user in the exclude list will evaluate to false. For more complex targeting, use the JSON filter..
        /// </summary>
        public static string AboutTargeting {
            get {
                return ResourceManager.GetString("AboutTargeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the time window filter to turn a feature on or off on a schedule..
        /// </summary>
        public static string AboutTimeWindow {
            get {
                return ResourceManager.GetString("AboutTimeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this filter?.
        /// </summary>
        public static string ConfirmDeleteFilter {
            get {
                return ResourceManager.GetString("ConfirmDeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disable this flag?.
        /// </summary>
        public static string ConfirmDisable {
            get {
                return ResourceManager.GetString("ConfirmDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to enable this flag?.
        /// </summary>
        public static string ConfirmEnable {
            get {
                return ResourceManager.GetString("ConfirmEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Flag.
        /// </summary>
        public static string CreateFlag {
            get {
                return ResourceManager.GetString("CreateFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Flag.
        /// </summary>
        public static string EditFlag {
            get {
                return ResourceManager.GetString("EditFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred validating filters.  Check the filters for details..
        /// </summary>
        public static string ErrorCheckFilters {
            get {
                return ResourceManager.GetString("ErrorCheckFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred deleting flag..
        /// </summary>
        public static string ErrorDeletingFlag {
            get {
                return ResourceManager.GetString("ErrorDeletingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag with this name already exists..
        /// </summary>
        public static string ErrorDuplicateName {
            get {
                return ResourceManager.GetString("ErrorDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error evaluating status of feature flag..
        /// </summary>
        public static string ErrorEvaluatingFlag {
            get {
                return ResourceManager.GetString("ErrorEvaluatingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred building the feature definition.  Check the filter configuration..
        /// </summary>
        public static string ErrorInvalidFilterConfiguration {
            get {
                return ResourceManager.GetString("ErrorInvalidFilterConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON format..
        /// </summary>
        public static string ErrorJsonInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorJsonInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON is required..
        /// </summary>
        public static string ErrorJsonRequired {
            get {
                return ResourceManager.GetString("ErrorJsonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required to create a flag..
        /// </summary>
        public static string ErrorNameRequired {
            get {
                return ResourceManager.GetString("ErrorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature flag not found..
        /// </summary>
        public static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage is required and must be between 0 and 100..
        /// </summary>
        public static string ErrorPercentageOutOfRange {
            get {
                return ResourceManager.GetString("ErrorPercentageOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one day of the week must be selected..
        /// </summary>
        public static string ErrorRecurrenceDaysOfWeekRequired {
            get {
                return ResourceManager.GetString("ErrorRecurrenceDaysOfWeekRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range end date is required..
        /// </summary>
        public static string ErrorRecurrenceEndDateRequired {
            get {
                return ResourceManager.GetString("ErrorRecurrenceEndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First day of week is required..
        /// </summary>
        public static string ErrorRecurrenceFirstDayOfWeekRequired {
            get {
                return ResourceManager.GetString("ErrorRecurrenceFirstDayOfWeekRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval is required and must be greater than zero..
        /// </summary>
        public static string ErrorRecurrenceIntervalRequired {
            get {
                return ResourceManager.GetString("ErrorRecurrenceIntervalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of occurrences is required..
        /// </summary>
        public static string ErrorRecurrenceNumberOfOccurrencesRequired {
            get {
                return ResourceManager.GetString("ErrorRecurrenceNumberOfOccurrencesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range end date value must be after the start date..
        /// </summary>
        public static string ErrorRecurrrenceEndDateValueOutOfRange {
            get {
                return ResourceManager.GetString("ErrorRecurrrenceEndDateValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred saving flag..
        /// </summary>
        public static string ErrorSavingFlag {
            get {
                return ResourceManager.GetString("ErrorSavingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is not a valid first occurrence..
        /// </summary>
        public static string ErrorStartDateNotValid {
            get {
                return ResourceManager.GetString("ErrorStartDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one user must be targeted or excluded..
        /// </summary>
        public static string ErrorTargetingNoUsers {
            get {
                return ResourceManager.GetString("ErrorTargetingNoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time or end time one is required..
        /// </summary>
        public static string ErrorTimeStartOrEndRequired {
            get {
                return ResourceManager.GetString("ErrorTimeStartOrEndRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time window duration cannot be longer than how frequently it occurs or be longer than 10 years..
        /// </summary>
        public static string ErrorTimeWindowDuration {
            get {
                return ResourceManager.GetString("ErrorTimeWindowDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be after start date..
        /// </summary>
        public static string ErrorTimeWindowEndBeforeStart {
            get {
                return ResourceManager.GetString("ErrorTimeWindowEndBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time cannot equal start time..
        /// </summary>
        public static string ErrorTimeWindowEndEqualStart {
            get {
                return ResourceManager.GetString("ErrorTimeWindowEndEqualStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Users.
        /// </summary>
        public static string ExcludeUsers {
            get {
                return ResourceManager.GetString("ExcludeUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add users to exclude..
        /// </summary>
        public static string ExcludeUsersIntro {
            get {
                return ResourceManager.GetString("ExcludeUsersIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters are conditions for determining the state of the feature flag.  Flags with no filters will always evaluate to false.  Create at least one filter to enable the flag..
        /// </summary>
        public static string FilterIntro {
            get {
                return ResourceManager.GetString("FilterIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Type.
        /// </summary>
        public static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag.
        /// </summary>
        public static string FlagLower {
            get {
                return ResourceManager.GetString("FlagLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string FlagsPlural {
            get {
                return ResourceManager.GetString("FlagsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string JSON {
            get {
                return ResourceManager.GetString("JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Filter.
        /// </summary>
        public static string JSONFilter {
            get {
                return ResourceManager.GetString("JSONFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Filter.
        /// </summary>
        public static string PercentageFilter {
            get {
                return ResourceManager.GetString("PercentageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string RangeTypeEndDate {
            get {
                return ResourceManager.GetString("RangeTypeEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No End.
        /// </summary>
        public static string RangeTypeNoEnd {
            get {
                return ResourceManager.GetString("RangeTypeNoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbered.
        /// </summary>
        public static string RangeTypeNumbered {
            get {
                return ResourceManager.GetString("RangeTypeNumbered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement Type.
        /// </summary>
        public static string RequirementType {
            get {
                return ResourceManager.GetString("RequirementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache cleared successfully..
        /// </summary>
        public static string SuccessClearingCache {
            get {
                return ResourceManager.GetString("SuccessClearingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag deleted successfully..
        /// </summary>
        public static string SuccessDeletingFlag {
            get {
                return ResourceManager.GetString("SuccessDeletingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag saved successfully..
        /// </summary>
        public static string SuccessSavingFlag {
            get {
                return ResourceManager.GetString("SuccessSavingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeting Filter.
        /// </summary>
        public static string TargetingFilter {
            get {
                return ResourceManager.GetString("TargetingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Users.
        /// </summary>
        public static string TargetUsers {
            get {
                return ResourceManager.GetString("TargetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add users to target..
        /// </summary>
        public static string TargetUsersIntro {
            get {
                return ResourceManager.GetString("TargetUsersIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string TimeEnd {
            get {
                return ResourceManager.GetString("TimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days of Week.
        /// </summary>
        public static string TimeRecurrenceDaysOfWeek {
            get {
                return ResourceManager.GetString("TimeRecurrenceDaysOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range End Date.
        /// </summary>
        public static string TimeRecurrenceEndDate {
            get {
                return ResourceManager.GetString("TimeRecurrenceEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Day of Week.
        /// </summary>
        public static string TimeRecurrenceFirstDayOfWeek {
            get {
                return ResourceManager.GetString("TimeRecurrenceFirstDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string TimeRecurrenceInterval {
            get {
                return ResourceManager.GetString("TimeRecurrenceInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Occurrences.
        /// </summary>
        public static string TimeRecurrenceNumberOfOccurrences {
            get {
                return ResourceManager.GetString("TimeRecurrenceNumberOfOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Type.
        /// </summary>
        public static string TimeRecurrenceRangeType {
            get {
                return ResourceManager.GetString("TimeRecurrenceRangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeats.
        /// </summary>
        public static string TimeRecurrenceType {
            get {
                return ResourceManager.GetString("TimeRecurrenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Window Filter.
        /// </summary>
        public static string TimeWindowFilter {
            get {
                return ResourceManager.GetString("TimeWindowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User (Identity.Name).
        /// </summary>
        public static string UserIdentity {
            get {
                return ResourceManager.GetString("UserIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Flags.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
    }
}
