//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeatureFlags.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Flags {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Flags() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeatureFlags.Resources.Flags", typeof(Flags).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the feature flag cache?.
        /// </summary>
        public static string ConfirmClearCache {
            get {
                return ResourceManager.GetString("ConfirmClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disable this flag?.
        /// </summary>
        public static string ConfirmDisable {
            get {
                return ResourceManager.GetString("ConfirmDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to enable this flag?.
        /// </summary>
        public static string ConfirmEnable {
            get {
                return ResourceManager.GetString("ConfirmEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will add any missing flags, and delete any deprecated ones. Are you sure you want to continue?.
        /// </summary>
        public static string ConfirmRefreshFlags {
            get {
                return ResourceManager.GetString("ConfirmRefreshFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Flag.
        /// </summary>
        public static string EditFlag {
            get {
                return ResourceManager.GetString("EditFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred deleting flag..
        /// </summary>
        public static string ErrorDeletingFlag {
            get {
                return ResourceManager.GetString("ErrorDeletingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with this name already exists..
        /// </summary>
        public static string ErrorDuplicateName {
            get {
                return ResourceManager.GetString("ErrorDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required to create a flag..
        /// </summary>
        public static string ErrorNameRequired {
            get {
                return ResourceManager.GetString("ErrorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred refreshing flags..
        /// </summary>
        public static string ErrorRefreshingFlags {
            get {
                return ResourceManager.GetString("ErrorRefreshingFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred saving flag..
        /// </summary>
        public static string ErrorSavingFlag {
            get {
                return ResourceManager.GetString("ErrorSavingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flag.
        /// </summary>
        public static string FlagLower {
            get {
                return ResourceManager.GetString("FlagLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string FlagsPlural {
            get {
                return ResourceManager.GetString("FlagsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Flags.
        /// </summary>
        public static string RefreshFlags {
            get {
                return ResourceManager.GetString("RefreshFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache cleared successfully..
        /// </summary>
        public static string SuccessClearingCache {
            get {
                return ResourceManager.GetString("SuccessClearingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag deleted successfully..
        /// </summary>
        public static string SuccessDeletingFlag {
            get {
                return ResourceManager.GetString("SuccessDeletingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags were refreshed successfully..
        /// </summary>
        public static string SuccessRefreshingFlags {
            get {
                return ResourceManager.GetString("SuccessRefreshingFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag saved successfully..
        /// </summary>
        public static string SuccessSavingFlag {
            get {
                return ResourceManager.GetString("SuccessSavingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Flags.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
    }
}
